---
title: "Hello, World!"
author: "Marisol Yake"
created: 2025-05-07
modified: 2025-05-14
---

# Hello, World!
In programming circles, there's a long-standing tradition that when embarking on the journey to learn a new programming language one should start by writing a single script that outputs the text "Hello, World!" to the terminal, indicating that we have all the baseline development requirements set up in order to program. From here, the possibilities are endless. I find that clearing this bar is often easier than how I build it up in my head, and after I do clear it I am all the more self-confident for it.

In the spirit of this tradition, I am taking my first steps into blogging with this post.

Hello world and welcome to my blog! My name is Marisol Yake and I am an undergraduate Information Science student at CU Boulder and a Data Analyst by trade. I have a love for research and understanding the impacts of information and communication technologies (ICTs) on human well-being and autonomy. Most recently, I have found a spark for public policy and I am following this thread until it ends! 

[Researching with the PIRL lab]

## Intentions
### Why am I making this blog?
- Creating an outlet for sharing what I care about and my thought process for applying to various topics.
- I want to practice academic humility and be receptive feedback, while also learning about topics from outside of my current wheelhouse.
- I have switched my undergraduate degree focus several times and it's really helped me see a lot of connections between professional and scientific topics. I want to share what I find where folks can find it.

### Who is this blog for?
- The science curious
- The interdisciplinary
- The ...

### What will I be posting?
- How-Tos: Technical and Use-case Tutorials (Data Analysis and Visualization esp.)
- Book Reports: Brief write-ups about the author(s) and the text.
- Chapter Review: Brief review and reflection on a selection of text.
- Public Data Analytics: Exploring questions of public interest through publicly available data.
- 

### How often do I intend to post?
- At least once a month.

